# Centralized style configuration for the Math Editor UI

# Font settings
FONT_FAMILY = "Courier"  # Changed to Segoe UI for better readability
LABEL_FONT_SIZE = 14
SECTION_LABEL_FONT_SIZE = 17
BUTTON_FONT_SIZE = 17
ENTRY_FONT_SIZE = 16
NOTES_FONT_SIZE = 16
SAT_TYPE_FONT_SIZE = 18
DOMAIN_BTN_FONT_SIZE = 15
ENTRY_LABEL_FONT_SIZE = 17

# Base colors
BASE_FONT_COLOR = "#333333"  # Darker text for better contrast
LABEL_FONT_COLOR = BASE_FONT_COLOR
SECTION_LABEL_FONT_COLOR = BASE_FONT_COLOR
BUTTON_FONT_COLOR = BASE_FONT_COLOR
ENTRY_FONT_COLOR = BASE_FONT_COLOR
NOTES_FONT_COLOR = BASE_FONT_COLOR
SAT_TYPE_FONT_COLOR = BASE_FONT_COLOR

# Neumorphic theme variables
NEUMORPH_BG_COLOR = "#f0f0f3"  # Main panel and widget background
NEUMORPH_SHADOW_DARK = "#b8b9be"  # Shadow color for depth
NEUMORPH_SHADOW_LIGHT = "#ffffff"  # Highlight color for raised effect
NEUMORPH_TEXT_COLOR = BASE_FONT_COLOR
NEUMORPH_GRADIENT_START = "#f7f7fa"
NEUMORPH_GRADIENT_END = NEUMORPH_BG_COLOR
NEUMORPH_RADIUS = 18

# Component-specific colors
BUTTON_BG_COLOR = NEUMORPH_BG_COLOR
BUTTON_HOVER_COLOR = "#f2f2f2"
BUTTON_BORDER_RADIUS = NEUMORPH_RADIUS
BUTTON_HIGHLIGHT_COLOR = "#cce5ff"

ENTRY_BG_COLOR = "#e8e8e8"  # Slightly darker for contrast
ENTRY_BORDER_RADIUS = 14
ENTRY_SHADOW_COLOR = "#c8c8c8"

NOTES_BG_COLOR = NEUMORPH_BG_COLOR
NOTES_BORDER_RADIUS = NEUMORPH_RADIUS
NOTES_PADDING = 16

# Layout and sizing
CONTROL_BTN_WIDTH = 240
CONTROL_BTN_HEIGHT = 56
ENTRY_HEIGHT = 44
NOTES_MIN_HEIGHT = 100
PADDING = 40
SPACING = 28
SECTION_SPACING = 18

# Shadow and highlight effects
SHADOW_OFFSETS = [8, 6, 4]  # Multiple layers for depth
SHADOW_ALPHAS = [40, 60, 90]  # Increasing opacity for each layer
HIGHLIGHT_ALPHAS = [30, 50, 80]  # Slightly less intense than shadows

# Math Domains specific
MATH_DOMAINS_BG = NEUMORPH_BG_COLOR
MATH_DOMAINS_BTN_BG = NEUMORPH_BG_COLOR
MATH_DOMAINS_BTN_HOVER = "#f2f2f2"
MATH_DOMAINS_BTN_TEXT = BASE_FONT_COLOR

# Left Panel specific
LEFT_PANEL_WIDTH = 820
LEFT_PANEL_BG = NEUMORPH_BG_COLOR
LEFT_PANEL_PADDING = PADDING
LEFT_PANEL_SPACING = SPACING

# Checkbox styling
CHECKBOX_SIZE = 22
CHECKBOX_PADDING = 8
CHECKBOX_BORDER_RADIUS = 12

# ... rest of the file remains unchanged ... 